dbt_cloud:
  outputs:
    dev:
      account: PZB96233
      database: analytics
      password: Sachin$123
      role: analyticsengineer
      schema: dbt_peruri
      threads: 3
      type: snowflake
      user: sachin
      warehouse: transform_wh
  target: dev

