sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: regions
      - name: nations
      - name: v_nations  
      - name: orders
      - name: lineitems
      - name: SUPPLIERS
      - name: partsupps
      - name: parts
        config:
          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 5, period: hour}
          loaded_at_field: o_orderdate::timestamp_ntz

  - name: src1
    database: MKMOTORS_DEV
    schema: STAGING
    tables:
      - name: STG_EMPLOYEES
  
  - name: src2
    database: ANALYTICS
    schema: DBT_PERURI
    tables:
      - name: SUPPLIERS

